# Generated by Django 3.0.8 on 2020-07-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='c_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('remember', models.BooleanField(default=False)),
                ('cuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='c_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('importancy', models.IntegerField(choices=[(1, 'Normal'), (2, 'Middle'), (3, 'High')])),
                ('remember', models.BooleanField(default=False)),
                ('times', models.IntegerField()),
                ('cuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.c_groups')),
            ],
        ),
    ]
