# Generated by Django 3.0.8 on 2020-07-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_cards',
            name='body',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='c_cards',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='c_cards',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
